language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - pip install -r requirements.txt
  - pip install tox
script: tox
# deploy:
#   provider: pypi
#   user: "Your username"
#   password:
#     secure: "Your encrypted password"
#   distributions: "sdist bdist_wheel"
#   on:
#     tags: true
#     branch: master
# notifications: 
#   slack:
#     secure: 